### ISSUE TITLE
Color formatter error persists in osx-64 Python 3.5

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/clyent#6]
Similar to the issue described in #5 but after the fix was merged in.  The error still happens on mac osx-64 in Python 3.5.  Here's an example of a chalmers command that triggers the color formatter error:

```
osx107-2:~ anaconda$ chalmers start --all
Starting programs anaconda-build-worker

Checking status of program anaconda-build-worker     ... [  [ERROR]
Traceback (most recent call last):
  File "/opt/anaconda/bin/chalmers", line 6, in <module>
    sys.exit(chalmers.scripts.chalmers_main.main())
  File "/opt/anaconda/lib/python3.5/site-packages/chalmers/scripts/chalmers_main.py", line 36, in main
    run_command(args, exit=exit)
  File "/opt/anaconda/lib/python3.5/site-packages/clyent/__init__.py", line 151, in run_command
    return args.main(args)
  File "/opt/anaconda/lib/python3.5/site-packages/chalmers/commands/start.py", line 47, in main
    print_colors('[  {=OK!c:green}  ]')
  File "/opt/anaconda/lib/python3.5/site-packages/clyent/colors/color_formatter.py", line 90, in print_colors
    write_item(text)
  File "/opt/anaconda/lib/python3.5/site-packages/clyent/colors/color_formatter.py", line 87, in write_item
    fmt.vformat(item, (), kwargs)
  File "/opt/anaconda/lib/python3.5/string.py", line 191, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/opt/anaconda/lib/python3.5/site-packages/clyent/colors/color_formatter.py", line 67, in _vformat
    self.format_field(obj, format_spec)
  File "/opt/anaconda/lib/python3.5/site-packages/clyent/colors/color_formatter.py", line 24, in format_field
    with Color(format_spec):
  File "/opt/anaconda/lib/python3.5/site-packages/clyent/colors/color.py", line 49, in __enter__
    self.current_color_id = set_color(self.color_id)
  File "/opt/anaconda/lib/python3.5/site-packages/clyent/colors/__init__.py", line 65, in set_color
    self.stream.write('\033[%sm' % (color_id or 0))
```

Note that the `chalmers` command does the `start` successfully but error is just in the writing of the colors to console.

**Comment by dsludwig** [comment]
Fixed in #8
